apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: iz0h30uz9-python 
  janus-idp.io/tekton: iz0h30uz9-python
  backstage.io/kubernetes-id: iz0h30uz9-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iz0h30uz9-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml